version: '3.2'

services:
    api:
        image: ghcr.io/engineer-man/piston
        container_name: piston_api
        restart: always
        privileged: true
        ports:
            - 2000:2000
        volumes:
            - ./data/piston/packages:/piston/packages
            - ./api/src/config.js:/piston_api/src/config.js
        tmpfs:
            - /tmp:exec
